---
- name: Ansible debug module in action
  hosts: all
  tasks:
  - name: print a simple statement
    command:  pwd
    register: myresult

  - name: display  myresult
    debug:
      msg: "{{myresult}}"
